### ISSUE TITLE
Baget add PathBase as editable env config

### ISSUE THREAD

**Issue by Dunge** [SimCubeLtd/simcube-helm-charts#17]
I'm trying to get [this ](https://artifacthub.io/packages/helm/simcube/baget)helm chart in my kubernetes cluster and host it via an ingress under a subpath of the main domain (/nuget).

I found [here ](https://github.com/loic-sharma/BaGet/issues/735) that a configuration variable named PathBase exists for this situation. You can see it in here: https://github.com/loic-sharma/BaGet/blob/main/src/BaGet.Core/Configuration/BaGetOptions.cs

This helm file deployment.yaml contains a few of these configuration variables, but not the PathBase one.

**Comment by prom3theu5** [comment]
Hi

Thanks for the suggestion - I've just added this in version 1.0.5 of the chart
You can set the value: `pathBase` which will be passed through to the deployment as an ENV Var.
